version: "3.4"


# NOTE: This _has _to start with `x-`
x-logging: &default-logging
  options:
    max-size: "20k"
    max-file: "10"

services:
  db:
    image: postgres:13-alpine
    env_file: .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data:delegated
    logging: *default-logging

volumes:
  db_data:
